server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    bus:
      trace:
        enable: true
    config:
      server:
        git:
          uri: https://github.com/wzlhello/demo-config.git #Git 仓库地址
          searchPaths: config #仓库路径
          username: xxxx #Git 仓库用户名
          password: xxxx #Git 仓库密码
          basedir: d:\config-repo
      label: master #仓库的分支
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/